import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./ui/nav";
import CartSidebar from "./ui/cartSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zarad Online Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-neutral-900 h-screen `}>
          <Nav />
          {/* <CartSidebar /> */}
          <div className="">
            {children}
          </div>

        </body>
    </html>
  );
}
